import React, { useEffect, useState } from 'react';
import { RefreshCw, Zap, Info, Loader2 } from 'lucide-react';
import { synth } from '../utils/audio';

interface Props {
  isInfinite: boolean;
  username: string;
  onSuccess: (score: number, guessesCount: number) => void;
}

export default function EmojiZeitgeistGame({ onSuccess }: Props) {
  const [emojis, setEmojis] = useState<string[]>([]);
  const [clues, setClues] = useState<string[]>([]);
  const [category, setCategory] = useState('');
  const [puzzleId, setPuzzleId] = useState('');
  const [guess, setGuess] = useState('');
  const [feedback, setFeedback] = useState('Loading a fresh emoji puzzle…');
  const [attempts, setAttempts] = useState<string[]>([]);
  const [hintLevel, setHintLevel] = useState(0);
  const [loading, setLoading] = useState(false);
  const [solved, setSolved] = useState(false);

  const fetchNew = async () => {
    setLoading(true);
    setSolved(false);
    setAttempts([]);
    setHintLevel(0);
    setGuess('');
    setFeedback('Decode the emojis into a movie, event, brand or idiom.');
    synth.playTargetSound('unlock');
    try {
      const r = await fetch('/api/games/zeitgeist/new', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' });
      const d = await r.json();
      setEmojis(d.emojis || []);
      setClues(d.clues || []);
      setCategory(d.category || '');
      setPuzzleId(d.id);
    } catch {
      setFeedback('Could not load a puzzle — try again.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchNew(); }, []);

  const submitGuess = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!guess.trim() || solved || loading) return;
    setLoading(true);
    try {
      const res = await fetch('/api/games/zeitgeist/guess', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ guess: guess.trim(), puzzleId }),
      });
      const result = await res.json();
      const updated = [...attempts, guess.trim()];
      setAttempts(updated);
      setGuess('');
      setFeedback(result.feedback || '');
      if (result.correct) {
        setSolved(true);
        synth.playTargetSound('win');
        onSuccess(Math.max(5, 100 - updated.length * 16 - hintLevel * 14), updated.length);
      } else {
        synth.playTargetSound('wrong');
      }
    } catch {
      setFeedback('Error checking your answer.');
    } finally {
      setLoading(false);
    }
  };

  const triggerClue = () => {
    synth.playTargetSound('click');
    if (hintLevel < clues.length) {
      setFeedback(`🔍 Clue: ${clues[hintLevel]}`);
      setHintLevel((h) => h + 1);
    } else {
      setFeedback('No more clues — take your best guess!');
    }
  };

  return (
    <div className="flex flex-col gap-5">
      <div className="retro-card p-4 bg-yellow-400/10 border-dashed border-2 flex items-start gap-3">
        <Info className="w-5 h-5 text-yellow-600 shrink-0 mt-0.5" />
        <div className="text-xs leading-relaxed font-mono">
          <span className="font-bold block mb-1">EMOJI — THE TREND TRANSLATOR</span>
          These emojis stand for a movie, event, brand or idiom. Type what they point to. Every puzzle is freshly generated by AI.
        </div>
      </div>

      <div className="flex justify-between items-center bg-[#1e1b13] text-white p-3.5 border-2 border-[#1e1b13]">
        <span className="font-display font-bold text-xs uppercase text-yellow-400 flex items-center gap-1.5">
          <Zap className="w-4 h-4 fill-yellow-400 text-yellow-400" />
          {category || 'Decrypting…'}
        </span>
        <button onClick={fetchNew} disabled={loading} className="text-[10px] font-mono hover:text-yellow-400 flex items-center gap-1 cursor-pointer">
          <RefreshCw className="w-3 h-3" /> New puzzle
        </button>
      </div>

      <div className="retro-card p-6 bg-white flex flex-col items-center gap-5">
        <div className="flex justify-center gap-3 p-4 bg-amber-500/5 border-2 border-[#1e1b13] w-full max-w-sm min-h-[5rem] items-center">
          {loading && emojis.length === 0 ? (
            <Loader2 className="w-7 h-7 animate-spin text-amber-500" />
          ) : (
            emojis.map((emoji, idx) => (
              <span key={idx} className="text-4xl drop-shadow select-none">{emoji}</span>
            ))
          )}
        </div>

        <div className="text-center font-display text-sm max-w-sm leading-relaxed bg-stone-50 py-3 px-4 border border-stone-200 w-full">
          {feedback}
        </div>

        {!solved && (
          <div className="w-full max-w-md flex flex-col gap-2">
            <form onSubmit={submitGuess} className="flex gap-2">
              <input
                type="text" value={guess} onChange={(e) => setGuess(e.target.value)}
                placeholder="e.g. Titanic"
                className="flex-1 px-4 py-3 bg-amber-50/20 border-2 border-[#1e1b13] font-mono text-sm focus:outline-none"
                disabled={loading}
              />
              <button type="submit" disabled={loading} className="accent-btn px-5 py-3 font-display font-bold cursor-pointer">
                {loading ? '…' : 'TRANSLATE'}
              </button>
            </form>
            <button type="button" onClick={triggerClue} className="text-left text-[11px] font-mono text-amber-700 hover:text-amber-800">
              ❔ Request a clue ({hintLevel}/{clues.length} used)
            </button>
          </div>
        )}

        {solved && (
          <button onClick={fetchNew} className="accent-btn px-5 py-2.5 font-display font-bold cursor-pointer flex items-center gap-2">
            <RefreshCw className="w-4 h-4" /> Next puzzle
          </button>
        )}

        {attempts.length > 0 && (
          <div className="w-full max-w-md mt-1">
            <span className="font-mono text-[9px] text-stone-400 uppercase tracking-widest block mb-1">Guesses</span>
            <div className="flex flex-wrap gap-1.5">
              {attempts.map((val, idx) => (
                <span key={idx} className="px-2 py-1 border border-stone-300 bg-stone-50 font-mono text-[10px] text-stone-500">{val}</span>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
